blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://spectrum.chat/graphql-java-kick/tools
    about: If you have a question ask it on Spectrum. All questions on GitHub will be deleted.
