name: Release
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Bintray
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: bintray
          server-username: BINTRAY_USER
          server-password: BINTRAY_PASS
      - name: Publish release
        run: mvn release:clean release:prepare release:perform -B -e -Pbintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.OSS_USER_TOKEN_KEY }}
          MAVEN_PASSWORD: ${{ secrets.OSS_USER_TOKEN_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
